#!/bin/bash
pushd $(dirname `which "$0"`) >/dev/null; fieldhome="$PWD"; popd >/dev/null

JDK=$fieldhome/jdk/win/jdk-10/bin/

out=$fieldhome/build/classes
out=${out/\/mnt\/c\//c:\//}
echo $out

fieldhome=${fieldhome/\/mnt\/c\//c:\//}
#JDK="/mnt/c/Program Files/Java/jdk-9.0.1/bin/"
java="$JDK"/java.exe

echo $fieldhome

"$java" \
    -Xdebug \
    -Xrunjdwp:server=y,transport=dt_socket,address=5005,suspend=n -Dorg.lwjgl.util.Debug=true \
    -DappDir=$fieldhome \
    -Xmx12g \
    -Xms8g \
    -javaagent:$fieldhome/build/field_agent.jar \
    -cp "$out;$fieldhome/build/field_linker.jar;$fieldhome/lib/;$fieldhome/lib/jars/*;$fieldhome/build/field_agent.jar" \
    -Djava.library.path=$fieldhome/win/lib/ \
    fieldagent.Trampoline ${*}

