#!/bin/bash
pushd $(dirname `which "$0"`) >/dev/null; fieldhome="$PWD"; popd >/dev/null

out=$fieldhome/out/production/
java=/usr/lib/jvm/jdk-9/bin/java


(echo '$fieldhome/f_server $java)' | at now)&

LD_LIBRARY_PATH=$out/fieldcore/linux64 $java -DappDir=$fieldhome -Xmx8g -Xms8g -javaagent:$fieldhome/out/artifacts/fieldagent_jar/fieldagent.jar  -cp $fieldhome/lib/linux64/:$fieldhome/out/artifacts/fieldlinker_jar/fieldlinker.jar:/Library/Java/JavaVirtualMachines/jdk1.9.0_40.jdk/Contents/Home/lib/tools.jar:$fieldhome/lib/*:$fieldhome/out/artifacts/fieldagent_jar/fieldagent.jar:$out/fieldcore/*:$out/fieldcore/orientdb/*:$out/fieldcore/guava-16.0.1.jar:$out/fieldcore/:$out/fielded/:$out/fielded/*:$out/fieldbox/:$out/fieldbox/*:$out/fieldnashorn/*:$out/fieldnashorn/:$out/fieldcef_macosx/*:$out/fieldcef_macosx/ -Djava.library.path=$fieldhome:$out/fieldcore/linux64/:/usr/local/lib/ fieldagent.Trampoline ${*}
