#!/bin/bash
pushd $(dirname `which "$0"`) >/dev/null; fieldhome="$PWD"; popd >/dev/null

out=$fieldhome/out/production/
java=/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/bin/java


(echo '$fieldhome/f_server "$java -addmods java.xml.bind" )' | at now)&

$java \
    -Xdebug \
    -XaddExports:jdk.management/com.sun.management.internal=ALL-UNNAMED \
    -Xrunjdwp:server=y,transport=dt_socket,address=5005,suspend=n -Dorg.lwjgl.util.Debug=true \
    -Djpy.pythonExecutable=/usr/local/opt/python3/bin/python3.4 \
    -Djpy.pythonLib=/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4/lib/python3.4/config-3.4m/libpython3.4.dylib \
    -Djpy.pythonPrefix=/usr/local/Cellar/python3/3.4.2_1/Frameworks/Python.framework/Versions/3.4 \
    -Xdock:icon=$fieldhome/f.png \
    -DappDir=$fieldhome -Xdock:name=Field \
    -Xmx8g \
    -Xms8g \
    -javaagent:$fieldhome/out/artifacts/fieldagent_jar/fieldagent.jar \
    -cp $fieldhome/lib/macosx/:$fieldhome/out/artifacts/fieldlinker_jar/fieldlinker.jar:/Library/Java/JavaVirtualMachines/jdk1.9.0_40.jdk/Contents/Home/lib/tools.jar:$fieldhome/lib/*:$fieldhome/out/artifacts/fieldagent_jar/fieldagent.jar:$out/fieldcore/orientdb/*:$out/fieldcore/guava-16.0.1.jar:$out/fieldcef_macosx/ \
    -Djava.library.path=$fieldhome:$out/fieldcore/macosx/:$out/fieldcore/helperapp.app/Contents/Java/:/usr/local/lib/ \
    fieldagent.Trampoline ${*}
