#!/bin/bash
pushd $(dirname `which "$0"`) >/dev/null; fieldhome="$PWD"; popd >/dev/null

out=$fieldhome/out/production/


/Library/Java/JavaVirtualMachines/jdk1.9.0_40.jdk/Contents/Home/bin/java -DdebugLinker -Xdock:icon=$fieldhome/f.png -DappDir=$fieldhome -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005 -Xdock:name=Field -Xmx4g -Xms4g -javaagent:$fieldhome/out/artifacts/fieldagent_jar/fieldagent.jar  -cp $fieldhome/out/artifacts/fieldlinker/fieldlinker.jar:/Library/Java/JavaVirtualMachines/jdk1.9.0_40.jdk/Contents/Home/lib/tools.jar:$fieldhome/lib/*:$fieldhome/out/artifacts/fieldagent_jar/fieldagent.jar:$out/fieldwork2/*:$out/fieldwork2/guava-16.0.1.jar:$out/fieldwork2/:$out/fielded/:$out/fielded/*:$out/fieldbox/:$out/fieldbox/*:$out/fieldnashorn/*:$out/fieldnashorn/:$out/fieldcef/*:$out/fieldcef/ -Djava.library.path=$fieldhome:$out/fieldwork2/macosx/:$out/fieldwork2/helperapp.app/Contents/Java/:/usr/local/lib/ fieldagent.Trampoline ${*}
