#!/bin/bash
pushd $(dirname `which "$0"`) >/dev/null; fieldhome="$PWD"; popd >/dev/null

out=$fieldhome/build/classes

# use this to set a jdk explicitly 
java=$fieldhome/jdk/osx/jdk-11.jdk/Contents/Home/bin/java

# use this is you a happy with what `java` resolves to
#java=java

echo Java Version is:
echo `java -version`

export FIELD2_LAUNCH=$fieldhome/$(basename $0)

$java \
    -splash:$fieldhome/lib/images/f.png \
    -Xrunjdwp:server=y,transport=dt_socket,address=5005,suspend=n -Dorg.lwjgl.util.Debug=false \
    -Xdock:icon=$fieldhome/lib/images/f.png \
    -DappDir=$fieldhome -Xdock:name=Field \
    -Xmx8g \
    -Xms8g \
    --add-exports java.base/sun.nio.ch=ALL-UNNAMED \
    --add-opens java.base/sun.nio.ch=ALL-UNNAMED \
    -javaagent:$fieldhome/build/field_agent.jar \
    -cp $out:$fieldhome/build/field_linker.jar:/Library/Java/JavaVirtualMachines/jdk1.9.0_40.jdk/Contents/Home/lib/tools.jar:$fieldhome/lib/:$fieldhome/lib/jars/*:$fieldhome/lib/jars/orientdb/*:$fieldhome/build/field_agent.jar:$fieldhome/../AUW/out/production/AUW/:$fieldhome/../AUW/lib/jvamp.jar:$fieldhome/../AUW/lib/ \
    -Djava.library.path=$fieldhome/osx/lib/:$fieldhome/osx/lib/helperapp.app/Contents/Java/:/usr/local/lib/ \
    fieldagent.Trampoline ${*}

