#!/bin/bash
pushd $(dirname `which "$0"`) >/dev/null; fieldhome="$PWD"; popd >/dev/null

out=$fieldhome/build/classes
out=`cygpath -w $out`
fieldhome=`cygpath -w $fieldhome`
JDK=$fieldhome/jdk/win/jdk-9.0.1/bin/
java="$JDK"/java

echo $fieldhome
ls $fieldhome/win/lib

if [ ! -f $JDK/field2/jdk/win/jdk-9.0.1/bin/server/classes.dsa ] ; then
	$java -Xshare:dump
fi


"$java" \
    -Xshare:on \
    -splash:$fieldhome/lib/images/f.png \
    --add-opens java.base/sun.nio.ch=ALL-UNNAMED \
    -Xdebug \
    -Xrunjdwp:server=y,transport=dt_socket,address=5005,suspend=n -Dorg.lwjgl.util.Debug=false \
    -DappDir=$fieldhome \
    -Xmx6g \
    -Xms2g \
    -Dfile.encoding=UTF-8 \
    -javaagent:$fieldhome/build/field_agent.jar \
    -cp "$out;$fieldhome/build/field_linker.jar;$fieldhome/lib/;$fieldhome/lib/jars/*;$fieldhome/build/field_agent.jar" \
    -Djava.library.path=$fieldhome/win/lib/ \
    fieldagent.Trampoline ${*}

