/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class field_graphics_FastJPEG */

#ifndef _Included_field_graphics_FastJPEG
#define _Included_field_graphics_FastJPEG
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT void JNICALL Java_field_graphics_FastJPEG_decompress
(JNIEnv *, jobject, jstring, jobject, jint, jint);

JNIEXPORT void JNICALL Java_field_graphics_FastJPEG_decompressFlipped
(JNIEnv *, jobject, jstring, jobject, jint, jint);

JNIEXPORT void JNICALL Java_field_graphics_FastJPEG_compress
(JNIEnv *, jobject, jstring, jobject, jint, jint);
    
JNIEXPORT void JNICALL Java_field_graphics_FastJPEG_decompressG
(JNIEnv *env, jobject jthis, jstring filename, jobject dest, jint width, jint height);

JNIEXPORT jlong JNICALL Java_field_graphics_FastJPEG_dimensionsFor
(JNIEnv *env, jobject jthis, jstring filename);

#ifdef __cplusplus
}
#endif
#endif
